import type { Task } from './types';

export const mockTasks: Task[] = [
  {
    id: 1,
    folderId: 1,
    title: 'Review frontend architecture',
    tag: 'frontend',
    priority: 'HIGH',
    status: 'todo',
    trackedMin: 45,
  },
  {
    id: 2,
    folderId: 1,
    title: 'Prepare FastAPI task schema',
    tag: 'backend',
    priority: 'MED',
    status: 'in_progress',
    trackedMin: 80,
  },
  {
    id: 3,
    folderId: 1,
    title: 'Write daily insight prompt',
    tag: 'ai',
    priority: 'MED',
    status: 'done',
    trackedMin: 30,
    completedAt: Date.now() - 3600000,
  },
  {
    id: 4,
    folderId: 1,
    title: 'вафывафыв',
    tag: '',
    priority: 'MED',
    status: 'in_progress',
    trackedMin: 0,
    comment: 'rбфцкопбфцкопбфцп',
  },
  {
    id: 5,
    folderId: 2,
    title: 'Learn dnd-kit basics',
    tag: 'react',
    priority: 'LOW',
    status: 'todo',
    trackedMin: 0,
  },
  {
    id: 6,
    folderId: 3,
    title: 'Plan evening routine',
    tag: 'life',
    priority: 'LOW',
    status: 'todo',
    trackedMin: 0,
  },
];
